version: "3.3"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Europe/London
    volumes:
      - ./.db:/config
    restart: unless-stopped

  baseball:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baseball
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./baseball.sql:/baseball.sql
      - ./results:/results

volumes:
  db:
