version: "3.3"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Europe/London
    volumes:
      - ./.db:/config
    restart: unless-stopped

  baseball:
    build:
      context: .
      dockerfile: Dockerfile
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./baseball.sql:/hw6/baseball.sql
      - ./script.sh:/hw6/script.sql
      - ./hw2.sql:/hw6/hw2/sql
      - ./results:/hw6/results
