version: "3.3"

networks:
  final-network:

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Europe/London
    volumes:
      - ./.db:/config
    restart: unless-stopped
    networks:
      final-network:
        aliases:
          - mariadb

  baseball:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baseball
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./baseball.sql:/baseball.sql
      - ./final.sql:/final.sql
      - ./results:/results
    networks:
      - final-network

volumes:
  db:
